// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwzxonj1G4PLaA6OGYxZAOwQPC6vciqPs',
    appId: '1:883685795836:web:f776bb75e124fb5cc9f479',
    messagingSenderId: '883685795836',
    projectId: 'medicine-reminder-auth',
    authDomain: 'medicine-reminder-auth.firebaseapp.com',
    storageBucket: 'medicine-reminder-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzxonj1G4PLaA6OGYxZAOwQPC6vciqPs',
    appId: '1:883685795836:android:f776bb75e124fb5cc9f479',
    messagingSenderId: '883685795836',
    projectId: 'medicine-reminder-auth',
    storageBucket: 'medicine-reminder-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwzxonj1G4PLaA6OGYxZAOwQPC6vciqPs',
    appId: '1:883685795836:ios:f776bb75e124fb5cc9f479',
    messagingSenderId: '883685795836',
    projectId: 'medicine-reminder-auth',
    storageBucket: 'medicine-reminder-auth.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwzxonj1G4PLaA6OGYxZAOwQPC6vciqPs',
    appId: '1:883685795836:macos:f776bb75e124fb5cc9f479',
    messagingSenderId: '883685795836',
    projectId: 'medicine-reminder-auth',
    storageBucket: 'medicine-reminder-auth.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwzxonj1G4PLaA6OGYxZAOwQPC6vciqPs',
    appId: '1:883685795836:windows:f776bb75e124fb5cc9f479',
    messagingSenderId: '883685795836',
    projectId: 'medicine-reminder-auth',
    storageBucket: 'medicine-reminder-auth.firebasestorage.app',
  );
}

